# Generated by Django 4.0.2 on 2022-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_contact_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='open',
            field=models.CharField(max_length=100),
        ),
    ]
